version: "2"
plugins:
  bandit:
    enabled: true
  editorconfig:
    enabled: true
  fixme:
    enabled: true
  pep8:
    enabled: true
  pylint:
    enabled: true
    PYTHONPATH:
      - src
    checks:
      bad-continuation:
        enabled: false
  sonar-python:
    enabled: true
    config:
      tests_patterns:
        - tests/unit/**
exclude_patterns:
  - ".vscode/**"
  - "docs/**/*"
  - "LICENSE"
